---
title: "CSC8634Project"
author: 'Saquib Mohiuddin Siddiqui, Student ID : 200636689'
date: "1/24/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
```

```{r include=FALSE}
# Load project
library("ProjectTemplate")
library(ggplot2)
load.project()

# Run code in analysis.R script
source("src/eda.R")
```

Viewing GPU Data set 
```{r}
head(gpu)
```
Summarizing GPU dataset 
```{r}
summary(gpu)
```


```{r}
df_gpu_scale = gpu[c(5,6,7,8)]
```

```{r}
head(df_gpu_scale)
```
```{r}

```


```{r}
df_gpu_scale = scale(df_gpu_scale)
```

```{r}
head(df_gpu_scale)
```

```{r}
cor(df_gpu_scale)
```


```{r}
cor(gpu$gpuUtilPerc, gpu$gpuMemUtilPerc)
```

```{r}
cor(gpu$powerDrawWatt, gpu$gpuTempC)
```


```{r}
head(application.checkpoints)
```

```{r}
table(application.checkpoints$eventType)
```


```{r}
table(application.checkpoints$eventName)
```


```{r}
table(task.x.y$level)
```
The visualization created is a zoomable "google maps style" map. In total we create 12 levels. Level 1 is zoomed right out and level 12 is zoomed right in. You will only see levels 4, 8 and 12 in the data as the intermediate level are derived in the tiling process.

```{r}
ym = table(task.x.y$level)
```


```{r}
barplot(ym, main = "Iterations to render Levels in Image", 
        xlab = "levels", ylab = "iterations", col = "darkred")
```


```{r}
cor(df_corr)
```

Drop column and obtain correlation matrix 


```{r}
pairs(df_gpu_scale)
```


```{r}
str(gpu)
```

